# Generated by Django 4.1.1 on 2024-05-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('read_date', models.DateField()),
                ('opinion', models.TextField()),
                ('recommended', models.BooleanField()),
                ('authors', models.ManyToManyField(to='Api_Books.author')),
            ],
        ),
    ]
